//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLabrary.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotecaprogramEntities : DbContext
    {
        public BibliotecaprogramEntities()
            : base("name=BibliotecaprogramEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alquileres> Alquileres { get; set; }
        public virtual DbSet<Autores> Autores { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Editoriales> Editoriales { get; set; }
        public virtual DbSet<Lectores> Lectores { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<solicitudes> solicitudes { get; set; }
    }
}
